rules:
  no-restricted-imports:
    - error
    - patterns:
        - lodash.*
        - microfrontends/*
        - modules/85-sto/*
        - '@sto/*'
      paths:
        - lodash
        - name: yaml
          importNames:
            - stringify
          message: Please use yamlStringify from @common/utils/YamlHelperMethods instead
            of this
        - name: react-router
          message: import from "react-router-dom" instead
        - name: microfrontends
          message: Import from 'microfrontends' is only allowed in child apps
